/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package example

import org.gradle.api.Project
import org.gradle.api.Plugin
import org.gradle.api.model.ObjectFactory
import org.gradle.api.provider.Property
import org.gradle.kotlin.dsl.*

class Gradle25412Plugin : Plugin<Project> {
    override fun apply(project: Project) {
        project.tasks.register("greeting") { task ->
            task.doLast {
                println("Hello from plugin 'example.greeting'")
            }
        }

        project.extra["p"] = project.objects.finalizedProperty<String>().value("foo")
    }
}

inline fun <reified T> ObjectFactory.finalizedProperty(): Property<T> =
    property(T::class.java).apply { finalizeValueOnRead() }
